---
- name: Install Python3 and Pip
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-venv
      - python-is-python3
    update_cache: true
  become: true

- name: Run a module inside a virtual environment
  become: true
  block:
    - name: Create VENV (not sure why this does not work from ansible.builtin.pip module)
      ansible.builtin.command:
        argv:
          - python
          - -m
          - venv
          - "{{ website_setup_venv_dir }}"
        creates: "{{ website_setup_venv_dir }}/bin/activate"

    - name: Install PyMySQL Python Module
      ansible.builtin.pip:
        name: pymysql
        virtualenv: "{{ website_setup_venv_dir }}"

- name: Install MariaDB Server (drop-in MySQL replacement)
  ansible.builtin.apt:
    name:
      - mariadb-server
  become: true

- name: Make Sure MariaDB is running
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true

- name: Test DB Connection
  community.mysql.mysql_query:
    query: select 1
    login_unix_socket: /var/run/mysqld/mysqld.sock
  become: true
  vars:
    ansible_python_interpreter: "{{ website_setup_venv_dir }}/bin/python"
