AWSTemplateFormatVersion: "2010-09-09"
Description: The template.

Resources:
  WebSereverLightsailInstance:
    Type: AWS::Lightsail::Instance
    Properties:
      InstanceName: bswt-web-2
      BlueprintId: debian_12
      BundleId: micro_3_0
      Networking:
        Ports:
          - CommonName: SSH
            AccessType: public
            FromPort: 22
            ToPort: 22
            Protocol: tcp
            AccessDirection: inbound
            Cidrs:
              - 0.0.0.0/0

          # - CommonName: HTTP
          # - CommonName: HTTPS

Outputs:
  BSWTWebsite2PublicIpAddress:
    Description: The public IP Address of the second BSWT Website.
    Value: !GetAtt WebSereverLightsailInstance.PublicIpAddress

  BSWTWebsite2UserName:
    Description: The username to connect to the second BSWT Website.
    Value: !GetAtt WebSereverLightsailInstance.UserName

  BSWTWebsite2SshKeyName:
    Description: The ssh key used to connect to the second BSWT Website.
    Value: !GetAtt WebSereverLightsailInstance.SshKeyName
